### PR TITLE
Fix error of building

### PR DESCRIPTION
**Pull request by Mitix-EPI**
The error is due to the deprecated installation of wine in the ubuntu vm.

### CODE REVIEW

**Comment by Mitix-EPI** [comment]
I just removed the windows build. The installation of wine is not working correctly on the github action instance.
Ignore the commits :)

**Comment by GuillaumeRobinSoriano** [comment]
I, Guillaume Robin, accept this wonderful pull request.

**Review by Cedani — APPROVED** [review]
Tkt

**Review by GuillaumeRobinSoriano — APPROVED** [review]
I approve

**Pull request merged**
